# Generated by Django 5.2.8 on 2025-12-06 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в избранное')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный альбом',
                'verbose_name_plural': 'Избранные альбомы',
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_albums', through='albums.FavoriteAlbum', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, добавившие в избранное'),
        ),
    ]
